### ISSUE TITLE
Add to `EVALUATION_TEMPLATES` in .env file for MCW orchestrator

### ISSUE THREAD

**Issue by thomasyu888** [nlpsandbox/nlpsandbox-controller#111]
### Is your proposal related to a problem?

Must add this configuration so that MCW will run Id and Contact submissions.
```json
{"9614804": "syn25585023",  "9614803": "syn25585023"}
```

Steps to update:

1. stop the orchestrator
2. edit the `.env`
3. start the orchestrator

**Comment by gkowalski** [comment]
updated .env to EVALUATION_TEMPLATES={"9614804": "syn25585023",  "9614803": "syn25585023"}

**Comment by gkowalski** [comment]
EVALUATION_TEMPLATES={"9614721":"syn25585023","9614719":"syn25585023","9614720":"syn25585023","9614804":"syn25585023","9614803":"syn25585023"}
