### ISSUE TITLE
Running docker to start docker-elk fails

### ISSUE THREAD

**Issue by gkowalski** [nlpsandbox/nlpsandbox-controller#137]
### Problem description

 Following the instructions in https://github.com/nlpsandbox/nlpsandbox-controller#readme for installation of the ELK stack. 
I get up to the point of starting the stack with the command : 

```docker compose -f docker-compose.yml -f extensions/logspout/logspout-compose.yml up -d --build```
 
and it fails. 

#### Steps to reproduce the issue

$ docker compose -f docker-compose.yml -f extensions/logspout/logspout-compose.yml up -d --build
 
unknown shorthand flag: 'f' in -f
See 'docker --help'.
 

#### Expected behavior

- starts the ELK Stack 

#### Extra information

 docker --version
Docker version 20.10.7, build f0df350

**Comment by gkowalski** [comment]
docker-compose -f docker-compose.yml -f extensions/logspout/logspout-compose.yml up -d --build

seems to be working

**Comment by gkowalski** [comment]
We are running the latest version of docker https://docs.docker.com/engine/release-notes/
uname -a 
Linux xxxxxx 3.10.0-1160.25.1.el7.x86_64 #1 SMP Wed Apr 28 21:49:45 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
[crdw@torres:~]$ docker --version
Docker version 20.10.7, build f0df350
[crdw@torres:~]$ docker compose
docker: 'compose' is not a docker command.
See 'docker --help'
[crdw@torres:~]$
and dont have docker "compose" . I believe the documentation should be updated to state the correct command per operating system.

**Comment by thomasyu888** [comment]
Interesting...  I have the newest version too except I have this command:

```
docker --version
Docker version 20.10.7, build f0df350
docker --help

Usage:  docker [OPTIONS] COMMAND

A self-sufficient runtime for containers

Options:
      --config string      Location of client config files (default "/Users/tyu/.docker")
  -c, --context string     Name of the context to use to connect to the daemon (overrides DOCKER_HOST env var and default context set with "docker context use")
  -D, --debug              Enable debug mode
  -H, --host list          Daemon socket(s) to connect to
  -l, --log-level string   Set the logging level ("debug"|"info"|"warn"|"error"|"fatal") (default "info")
      --tls                Use TLS; implied by --tlsverify
      --tlscacert string   Trust certs signed only by this CA (default "/Users/tyu/.docker/ca.pem")
      --tlscert string     Path to TLS certificate file (default "/Users/tyu/.docker/cert.pem")
      --tlskey string      Path to TLS key file (default "/Users/tyu/.docker/key.pem")
      --tlsverify          Use TLS and verify the remote
  -v, --version            Print version information and quit

Management Commands:
  builder     Manage builds
  buildx*     Build with BuildKit (Docker Inc., v0.5.1-docker)
  compose*    Docker Compose (Docker Inc., 2.0.0-beta.4)
  ```

**Comment by thomasyu888** [comment]
Ah ... It only works for Docker desktop for now. Hmmm .... I'll fix the instructions to use docker-compose instead since most these services will be run on an instance of some type
