### ISSUE TITLE
Update max concurrent submission and max memory available

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/nlpsandbox-controller#144]
The controller (infra) EC2 has 16 GB of memory.

- Our doc says that each submission has access to 4 GB of memory.
- I believe that the controller is configured to run max 4 concurrent submissions (4x 4GB + system memory => risk of out of memory)?

The CloudWatch data bellow shows that one of the Spark NLP model developed use 3.2 GB. This is not an issue in itself but the margin of available memory is thin.

![image](https://user-images.githubusercontent.com/3056480/128966537-78793cfa-9081-4ee3-979b-92a386d8f4f1.png)

### Proposal

- Set max concurrent memory to 2.
- Set max memory / submission to 7 GB. This leaves about 4G available for the system and controller.

**Comment by thomasyu888** [comment]
@tschaffter did you want me to bump the instance to have 32gb memory?

**Comment by tschaffter** [comment]
@thomasyu888 Would that be a `t3.2xlarge`? I don't think we need to pay that much for now (that would be about 3k/year with [on-demand](https://aws.amazon.com/ec2/pricing/on-demand/)). We can still to max 2 submissions with 7 GB / each and upgrade the memory when we get a request - and increase the max number of submissions needed.

@gkowalski Would it be OK to increase the amount of memory allocated to each submission to 7 GB at MCW data site?

**Comment by tschaffter** [comment]
@thomasyu888 Is the change brought by the above PR effective and running on Sage Data Site? In the future when we update compute resources spec, we should reach an agreement among all data sites. Can you document the operation that @gkowalski should follow to apply this change to the MCW data site?

**Comment by tschaffter** [comment]
@thomasyu888 Do you systematically create a new release of the controller before updating the infrastructure? It's important that we keep track of the change logs. Maybe use `release-it` as to automatically generate the changelogs for the releases. I use this approach in other projects. I can show you how I do it.

**Comment by thomasyu888** [comment]
@tschaffter the change logs can be seen with every PR that starts with "Stable release".  Due to the constant changing of the controller, I stopped creating release tags as I don't use the release tags for the controller infra.

**Comment by thomasyu888** [comment]
@tschaffter also MCW doesn't need to do anything. And yes it is already implemented for the main queues

**Comment by tschaffter** [comment]
> also MCW doesn't need to do anything.

@thomasyu888 But how is their infra updated so that they start allocating 7 GB of memory to submissions?

**Comment by thomasyu888** [comment]
@tschaffter They don't need to update anything, its part of of the controller workflow here: https://github.com/nlpsandbox/nlpsandbox-controller/blob/develop/start_service.py#L44. 

MCW just needs to confirm that they can handle 7GB memory * number of concurrent submissions they allow.

**Comment by tschaffter** [comment]
@thomasyu888 So to be more specific, this means that the update is already effective at MCW site? If yes, did you get the confirmation from @gkowalski that this change could be applied to MCW prior to making the update?

I'm trying to clarify things and ensure we have a robust SOP. Once again, it's important that all data site can confirm that they can support changes made to the compute resources made available to a tool before implementing the change.

**Comment by tschaffter** [comment]
I will close this ticket once I get the confirmation that the change has been applied to Sage data site and MCW data site.

**Comment by thomasyu888** [comment]
@tschaffter it's been applied already with the linked PR

**Comment by gkowalski** [comment]
SO we're up to 7GB * ( I think 10 concurrent process ) .. 70GB. We can handle that.  Where is that 10 concurrent values set so I can document it ?

**Comment by tschaffter** [comment]
@gkowalski By processes, do you mean submissions? The update that Tom has applied also set the number of max concurrent submission from 4 to 2 (see above).

@thomasyu888 While all data sites should give the same compute resources to a submission - mainly memory in this discussion - data sites may allow to run different number of concurrent submissions depending on the size of their server. Is this something that is possible with the current infrastructure?

**Comment by gkowalski** [comment]
Yes we will no problem running 2x7Gb

**Comment by thomasyu888** [comment]
@tschaffter yes, the number of concurrent submissions running is specified in the .env file of the orchestrator and is separate from this repo

**Comment by tschaffter** [comment]
Gotcha. Let's wait for @gkowalski to be back from vacation so that he can update `.env` before closing this ticket.

**Comment by tschaffter** [comment]
Done
