### ISSUE TITLE
Remove the property Note.note_name from the note sent to a PHI annotator

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/nlpsandbox-controller#146]
### Is your proposal related to a problem?

Not really an issue but found while searching why the Spark NLP tool succeed on the date annotation task but fails on the other tasks.

### Describe the solution you'd like

The endpoint used by the controller to annotate a clinical note takes as input a `Note` object. However, MCW logs show that this object include an extra property `note_name` that is not part of the Note schemas. While this does not appear to affect the Spark NLP tool, the property `Note.note_name` is not expected by tools and may lead to error, e.g. if they case the JSON payload to a Class object and this cast fails because of the unknown property.

The solution is to remove the property `Note.note_name` from the Note object sent to annotators.

### Describe alternatives you've considered

-

### Additional context

Tagging @gkowalski who helps me troubleshooting the Spark NLP issue.

**Comment by thomasyu888** [comment]
@tschaffter this is duplicated of this https://github.com/nlpsandbox/nlpsandbox-client/issues/132. Please review this original ticket and comment.
