### ISSUE TITLE
Figure out how to return service logs to participants 

### ISSUE THREAD

**Issue by thomasyu888** [nlpsandbox/nlpsandbox-controller#16]
Currently, Docker container logs are captured no the ELK stack, but participants do not have access to this.   Logs still have to be returned somehow.

**Comment by tschaffter** [comment]
That's a good point. We still don't want to return logs when running on evaluation data. What I'll do is create a second dataset in the data node that we can use for validation. Log generated during validation must be returned to participants (#17 ).

But that doesn't respond to your question. :) We probably need to export logs from ELK to somewhere participants can retrieve them. It would be a serious security concern if we where to give participants access to the ELK instance.

Currently, the only secure way that we have to return logs is likely to push them to Synapse as we do in most challenges. The controller would need a step where it retrieves the log of a submission from ELK. Does ELK provides an API to access logs?

Thoughts?

**Comment by thomasyu888** [comment]
I'm looking into pulling logs of a submission from ELK.  That being said, the streaming of log files will be sort of an issue.  Lets say there a thousand notes to annotate, and for each note, there are 5 lines of stdout from the service, this means that we are returning at least 5000 lines of logs to the user.  

The ELK extension we are using simply interacts with the docker API to populate the dashboard with logs.   Ultimately, I wish we had a way to give certain users permissions to certain logs on the ELK stack.  This way participants had a dynamic way of viewing their logs.  For now, I would most likely just retrieve logs from the annotation service after each clinical note has been annotated.

**Comment by tschaffter** [comment]
For advanced security, we could forward logs with log security risk to a second ELK instance that users can log on, to make sure that users can not log on an ELK stack that may contain sensitive log as the ones generated when using a "private" dataset.

**Comment by thomasyu888** [comment]
Thats what I was thinking, but we don't want users to be able to access other user's logs.  Due to this, I think this would be a nice to have, but needs some refinement.

**Comment by thomasyu888** [comment]
@tschaffter ,  Currently an ugly way of returning logs to participants:

<img width="1672" alt="Screen Shot 2020-12-22 at 9 42 18 AM" src="https://user-images.githubusercontent.com/10556275/102838839-19687480-443a-11eb-9379-30f05c98360b.png">

1. Go to the search you want
2. query for a specific submission
3. Click inspect
4. Click response
5. Click the copy command and parse logs with python. (Just json)

**Comment by tschaffter** [comment]
Tracked in https://github.com/nlpsandbox/nlpsandbox-website-synapse/issues/3
