### ISSUE TITLE
Set up ELK on it's own instance

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/nlpsandbox-controller#21]
- [ ] Respect ELK recommendation on heap, see section [Heap considerations for the ELK stack of this IBM doc)](https://www.ibm.com/support/knowledgecenter/SSVH2B_1.1.0/supported_system_config/system_reqs.html)

Note on heap requirement:

> An Ubuntu 20.04 server with 4GB RAM and 2 CPUs set up with a non-root sudo user. You can achieve this by following the Initial Server Setup with Ubuntu 20.04.For this tutorial, we will work with the minimum amount of CPU and RAM required to run Elasticsearch. Note that the amount of CPU, RAM, and storage that your Elasticsearch server will require depends on the volume of logs that you expect.

Source: [How To Install Elasticsearch, Logstash, and Kibana (Elastic Stack) on Ubuntu 20.04](https://www.digitalocean.com/community/tutorials/how-to-install-elasticsearch-logstash-and-kibana-elastic-stack-on-ubuntu-20-04)

=> Select an AWS EC2 t2.medium

Use this ticket to document the steps used to install ELK and configure the EC2.

**Comment by thomasyu888** [comment]
I have an elk instance running on its own now.  The question is why don't we want to utilize docker for elk?

**Comment by tschaffter** [comment]
> The question is why don't we want to utilize docker for elk?

@thomasyu888 We definitively want to install https://github.com/nlpsandbox/docker-elk. If your question originate from me posting the Digital Ocean article, I posted it because to goes beyond just installing ELK, e.g. how to setup an Nginx proxy.

> AWS appears to just have the ELK stack as a service that we can create.

This is something that we can investigate, especially if one day we come up with a CloudFormation template to deploy the entire stack and to benefit from high-performance AWS solution. However I need to come up first with a solution that is AWS agnostic to open our infrastructure to users and institutions that do not use AWS.

**Comment by thomasyu888** [comment]
Taking some notes:

Set up ELK on an own instance.  Then on instances that run submissions

1.  Build custom logspout docker from docker-elk/extensions folder
2. Run this command
```
docker run --name="logspout" \
    --volume=/var/run/docker.sock:/var/run/docker.sock \
    -e ROUTE_URIS=logstash://logstashurl:5000 \
    -e LOGSTASH_TAGS=docker-elk \
    built-logspout-image

```

**Comment by tschaffter** [comment]
> Docker images ran on other instances will now appear on ELK.

How do you configure Docker containers running on other EC2 to publish their logs to ELK?

**Comment by thomasyu888** [comment]
That docker command is how you do it
