### ISSUE TITLE
Identify how to "combine" multiple API services so that they appear as one on AWS

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/nlpsandbox-controller#22]
The solution should support services hosted on different instances.

**Comment by thomasyu888** [comment]
Are you saying to have all the services be under one domain, but hosted on different ec2s?

nlp-sandbox.io:8080 (datanode)
nlp-sandbox.io:9000 (textdateannotator)
etc...

One thing that we haven't looked into is API gateway: https://aws.amazon.com/api-gateway/

**Comment by tschaffter** [comment]
I envision to piece together the following APIs that would be visible as one service from the user perspective.

- Data node
- PHI deidentifier
- Text annotator

The base URL for all these service would be the same, like

nlpsandbox.org/api/v1/create_dataset => directed to data node
nlpsandbox.org/api/v1/deidentify_note => directed to phi deidentifier

One step in that direction is that I took care of preventing path overlap between the different APIs that we have defined in the schemas repository.

**Comment by tschaffter** [comment]
@thomasyu888 The above proposal is kind of separate from the benchmarking infrastructure. It would enable an hospital to say, OK let's take a data node, a performance date annotator, person name annotator, etc. and an implementation of a PHI Deidentifier and let's deploy that as an ecosystem that is kind of a "mini Google Cloudhealth API" ready for production use.

**Comment by thomasyu888** [comment]
@tschaffter : I found this post: https://stackoverflow.com/questions/51864951/how-to-merge-multiple-micro-services-behind-single-api-gateway.

**Comment by tschaffter** [comment]
## Update

The idea is to have a cloud API similar to Google Healthcare API that provide Data Node and PHI Deidentifier. However this has nothing to do with the controller, so I'm closing this ticket.
