### ISSUE TITLE
Validation of the annotation service

### ISSUE THREAD

**Issue by thomasyu888** [nlpsandbox/nlpsandbox-controller#31]
The submitted service itself needs to be validated.

* Get if root is redirected to service endpoint 
* check if service object is same as this schema: https://github.com/nlpsandbox/nlpsandbox-schemas/blob/develop/json-schema/schemas/service.json
* check if POST call works per annotator

**Comment by thomasyu888** [comment]
This can probably be done in the same way as #32

**Comment by tschaffter** [comment]
Yes
