### ISSUE TITLE
Validation of the annotation service's POST output

### ISSUE THREAD

**Issue by thomasyu888** [nlpsandbox/nlpsandbox-controller#32]
Currently the annotated notes aren't validated.  Will need to validate the annotation results against the schema.  Currently, there is only: https://github.com/nlpsandbox/nlpsandbox-schemas/blob/develop/openapi/commons/components/schemas/TextDateAnnotation.yaml.

**Comment by tschaffter** [comment]
@thomasyu888 We may not need a JSON schema for this validation. One of the microservice client generated with openapi-generator should provide a Python model for the annotation output. This model can be used to validate the response received by the annotator. Here is [an example](https://github.com/nlpsandbox/nlpsandbox-client/blob/ebdb7c28554b989128f159838e02fa76327b9d8b/textdateannotator/models/text_date_annotation.py#L159-L172) of code generated for the Date Annotator Client that checks that the confidence level generated are included between 0 and 100.

**Comment by thomasyu888** [comment]
@tschaffter, nice suggestion!  Its on my list of todos to add cli to ping the annotation service with the `nlpsandbox-client`.  I'm just doing a raw curl call right now.

**Comment by thomasyu888** [comment]
Hmm, here is an example of a validation error (of a service object) / When i am calling a docker command.

```
'Traceback (most recent call last):\n  File "/usr/local/bin/nlp-cli", line 8, in <module>\n    sys.exit(main())\n  File "/usr/local/lib/python3.8/site-packages/nlpsandboxclient/cli/__main__.py", line 15, in main\n    cli()\n  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__\n    return self.main(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main\n    rv = self.invoke(ctx)\n  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke\n    return callback(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/nlpsandboxclient/cli/evaluate.py", line 80, in get_annotator_service\n    service = client.get_annotator_service_info(\n  File "/usr/local/lib/python3.8/site-packages/nlpsandboxclient/client.py", line 244, in get_annotator_service_info\n    service_info = service_api.service()\n  File "/usr/local/lib/python3.8/site-packages/textdateannotator/api/service_api.py", line 62, in service\n    return self.service_with_http_info(**kwargs)  # noqa: E501\n  File "/usr/local/lib/python3.8/site-packages/textdateannotator/api/service_api.py", line 129, in service_with_http_info\n    return self.api_client.call_api(\n  File "/usr/local/lib/python3.8/site-packages/textdateannotator/api_client.py", line 365, in call_api\n    return self.__call_api(resource_path, method,\n  File "/usr/local/lib/python3.8/site-packages/textdateannotator/api_client.py", line 209, in __call_api\n    return_data = self.deserialize(response_data, response_type)\n  File "/usr/local/lib/python3.8/site-packages/textdateannotator/api_client.py", line 281, in deserialize\n    return self.__deserialize(data, response_type)\n  File "/usr/local/lib/python3.8/site-packages/textdateannotator/api_client.py", line 320, in __deserialize\n    return self.__deserialize_model(data, klass)\n  File "/usr/local/lib/python3.8/site-packages/textdateannotator/api_client.py", line 661, in __deserialize_model\n    instance = klass(**kwargs)\n  File "/usr/local/lib/python3.8/site-packages/textdateannotator/models/service.py", line 79, in __init__\n    self.license = license\n  File "/usr/local/lib/python3.8/site-packages/textdateannotator/models/service.py", line 174, in license\n    raise ValueError(\nValueError: Invalid value for `license` (Apache-2.0), must be one of [\'afl-3.0\', \'apache-2.0\', \'artistic-2.0\', \'bsl-1.0\', \'bsd-2-clause\', \'bsd-3-clause\', \'bsd-3-clause-clear\', \'cc\', \'cc0-1.0\', \'cc-by-4.0\', \'cc-by-sa-4.0\', \'wtfpl\', \'ecl-2.0\', \'epl-1.0\', \'epl-2.0\', \'eupl-1.1\', \'agpl-3.0\', \'gpl\', \'gpl-2.0\', \'gpl-3.0\', \'lgpl\', \'lgpl-2.1\', \'lgpl-3.0\', \'isc\', \'lppl-1.3c\', \'ms-pl\', \'mit\', \'mpl-2.0\', \'osl-3.0\', \'postgresql\', \'ofl-1.1\', \'ncsa\', \'unlicense\', \'zlib\']\n'
```

It is actually too long to save this traceback, so I would truncate this error by the last 500 characters and it would be:

```
" 174, in license\n    raise ValueError(\nValueError: Invalid value for `license` (Apache-2.0), must be one of ['afl-3.0', 'apache-2.0', 'artistic-2.0', 'bsl-1.0', 'bsd-2-clause', 'bsd-3-clause', 'bsd-3-clause-clear', 'cc', 'cc0-1.0', 'cc-by-4.0', 'cc-by-sa-4.0', 'wtfpl', 'ecl-2.0', 'epl-1.0', 'epl-2.0', 'eupl-1.1', 'agpl-3.0', 'gpl', 'gpl-2.0', 'gpl-3.0', 'lgpl', 'lgpl-2.1', 'lgpl-3.0', 'isc', 'lppl-1.3c', 'ms-pl', 'mit', 'mpl-2.0', 'osl-3.0', 'postgresql', 'ofl-1.1', 'ncsa', 'unlicense', 'zlib']\n"
```

Are you ok with an error message like this?

**Comment by tschaffter** [comment]
It looks like the message that we should return is (extracted from above):

```
Invalid value for license (Apache-2.0), must be one of ['afl-3.0', 'apache-2.0', 'artistic-2.0', 'bsl-1.0', 'bsd-2-clause', 'bsd-3-clause', 'bsd-3-clause-clear', 'cc', 'cc0-1.0', 'cc-by-4.0', 'cc-by-sa-4.0', 'wtfpl', 'ecl-2.0', 'epl-1.0', 'epl-2.0', 'eupl-1.1', 'agpl-3.0', 'gpl', 'gpl-2.0', 'gpl-3.0', 'lgpl', 'lgpl-2.1', 'lgpl-3.0', 'isc', 'lppl-1.3c', 'ms-pl', 'mit', 'mpl-2.0', 'osl-3.0', 'postgresql', 'ofl-1.1', 'ncsa', 'unlicense', 'zlib']
```

**Comment by tschaffter** [comment]
My guess is that the service object can be a frequent source of invalid submission, so it's definitively worth making the feedback as user friendly as possible. Maybe a combination of a high-level message like yours ""API /service endpoint not implemented or implemented incorrectly. Make sure correct service object is returned."" and the details information I copied pasted above that we can retrieve programmatically.

**Comment by thomasyu888** [comment]
@tschaffter ,  I think that will be a little bit complicated.  This is because we can only annotate with a max of 500 characters..  So the combination of above would cause a cutoff:

> "API /service endpoint not implemented or implemented incorrectly. Make sure correct service object is returned. + 'bsd-2-clause', 'bsd-3-clause', 'bsd-3-clause-clear', 'cc', 'cc0-1.0', 'cc-by-4.0', 'cc-by-sa-4.0', 'wtfpl', 'ecl-2.0', 'epl-1.0', 'epl-2.0', 'eupl-1.1', 'agpl-3.0', 'gpl', 'gpl-2.0', 'gpl-3.0', 'lgpl', 'lgpl-2.1', 'lgpl-3.0', 'isc', 'lppl-1.3c', 'ms-pl', 'mit', 'mpl-2.0', 'osl-3.0', 'postgresql', 'ofl-1.1', 'ncsa', 'unlicense', 'zlib']"

I do agree that it's important to provide users with a good message.  I can hardcode some validation messages.  I guess its difficult to test these until we start getting submissions.  (Or purposely create invalid submissions and see the error messages)

**Comment by tschaffter** [comment]
Update on the approach adopted: we decided to adopt simple high-level error message in this early stage of the development, then will add details when needed and time permits.
