### ISSUE TITLE
Support multiple data hosting sites

### ISSUE THREAD

**Issue by thomasyu888** [nlpsandbox/nlpsandbox-controller#41]
A bigger problem right now is that a submission isn't easily run on multiple queues unless we adopt the COVID / EHR infrastructure.   The issue is that once a submission is put in EVALUATION_IN_PROGRESS, it is only run on one infrastructure.

Due to this, the currently working solution is:

1. Participants submit to a main queue
2. services are validated
3. A service account submits to internal queues which are then linked to different data hosting sites
4. Each of these internal queues then start the services and annotate the notes.
5. results are all propagated back to the main queue.

Ideally what happens is...

1. A submission happens
2. Workers on each of these data hosting sites recognizes that a submission has happened
3. Starts the evaluation of submission process

But the ideal scenario is still largely WIP.

**Comment by tschaffter** [comment]
@thomasyu888 I suspect that we will address this problem in https://github.com/Sage-Bionetworks/submission-schemas. I'm assigning this ticket for the sprint 21.2 (February), after we launch the NLP Sandbox this month.

**Comment by tschaffter** [comment]
@thomasyu888 This ticket is too generic and I'm thinking to close it. We previously discussed that our current framework could support multiple data hosting sites. We are currently working with MCW to help them deploy a data hosting site (tracked in https://github.com/nlpsandbox/nlpsandbox/issues/6). When we receive a submission, we (Sage) would first run it on a public dataset as a sort of validation before enabling other sites to evaluate the submission on their own data.
