### ISSUE TITLE
Add '_type' into scoring in convert_score.cwl once goldstandard is updated

### ISSUE THREAD

**Issue by thomasyu888** [nlpsandbox/nlpsandbox-controller#42]
Currently:

```
          # key = f"{annotator_type}_type"
          # for types in scores[key]:
          #     new_scores_dict[f"type_{types['metric']}"] = types['value']
```
Is commented out, because `dateFormat` is blank for the goldstandard.  Once it is filled in, then this code can be added.

**Comment by tschaffter** [comment]
@thomasyu888 The property `dateFormat` is optional and thus should never be expected. Note that we will probably not have a gold standard for `dateFormat` by the launch of the NLP Sandbox. However we should still be able to accept predictions that we may later evaluate internally. For now, the controller should ignore `dateFormat` OR better, 1) reduce the gold standard to date object that have a value for `dateFormat` (currently 0 date objects) and 2) evaluate the ability of a tool to predict `dateFormat` based on this subset of date objects (currently 0 date objects, thus returning NA or "").

**Comment by thomasyu888** [comment]
@tschaffter,  based on what you said, lets take the example prediction and goldstandard:

```
nlp-cli evaluate prediction --pred_filepath prediction_1.json --gold_filepath goldstandard_1.json --eval_type date
{'date_location': [{'metric': 'F1', 'value': 0.75, 'type': 'instance', 'mode': 'relax'}, {'metric': 'precision', 'value': 0.75, 'type': 'instance', 'mode': 'relax'}, {'metric': 'recall', 'value': 0.75, 'type': 'instance', 'mode': 'relax'}, {'metric': 'F1', 'value': 0.5, 'type': 'instance', 'mode': 'strict'}, {'metric': 'precision', 'value': 0.5, 'type': 'instance', 'mode': 'strict'}, {'metric': 'recall', 'value': 0.5, 'type': 'instance', 'mode': 'strict'}, {'metric': 'F1', 'value': 0.67, 'type': 'token', 'mode': 'strict'}, {'metric': 'precision', 'value': 0.6, 'type': 'token', 'mode': 'strict'}, {'metric': 'recall', 'value': 0.75, 'type': 'token', 'mode': 'strict'}], 'date_type': [{'metric': 'F1', 'value': 0.5}, {'metric': 'precision', 'value': 0.5}, {'metric': 'recall', 'value': 0.5}]}
{'date_location': [{'metric': 'F1', 'value': 0.75, 'type': 'instance', 'mode': 'relax'}, {'metric': 'precision', 'value': 0.75, 'type': 'instance', 'mode': 'relax'}, {'metric': 'recall', 'value': 0.75, 'type': 'instance', 'mode': 'relax'}, {'metric': 'F1', 'value': 0.5, 'type': 'instance', 'mode': 'strict'}, {'metric': 'precision', 'value': 0.5, 'type': 'instance', 'mode': 'strict'}, {'metric': 'recall', 'value': 0.5, 'type': 'instance', 'mode': 'strict'}, {'metric': 'F1', 'value': 0.67, 'type': 'token', 'mode': 'strict'}, {'metric': 'precision', 'value': 0.6, 'type': 'token', 'mode': 'strict'}, {'metric': 'recall', 'value': 0.75, 'type': 'token', 'mode': 'strict'}], 'date_type': [{'metric': 'F1', 'value': 0.5}, {'metric': 'precision', 'value': 0.5}, {'metric': 'recall', 'value': 0.5}]}
```

You'll notice that there is a `date_location` and `date_type`.  Based on what you just said, `type_f1`, `type_precision`, and `type_recall` won't always be available since the `...Format` field isn't always necessary.  Due to this, do you think those 3 value should just be NA.  Tagging @yy6linda for thoughts as well.

**Comment by yy6linda** [comment]
I added a [description](https://docs.google.com/document/d/1R1pQRx-6iURjJmmtLyGXVAMMA0ulD3RygHJc_dQ14hw/edit#) (under `leaderboard outlook`) of how each scoring matrix is calculated based on current [goldstandard](https://github.com/nlpsandbox/nlpsandbox-client/blob/develop/examples/example-patient-bundles.json).

**Comment by yy6linda** [comment]
For the three values (type_f1....)  that Tom mentioned, only the type_f1_address will have values, the other will be NA due to the missing in our current gold standards.

**Comment by thomasyu888** [comment]
No longer need `Type` since this PR: https://github.com/nlpsandbox/nlpsandbox-client/pull/91.  Closing.
