### ISSUE TITLE
Create CF templates for infrastructure

### ISSUE THREAD

**Issue by thomasyu888** [nlpsandbox/nlpsandbox-controller#48]

**Comment by tschaffter** [comment]
Add the CF template to this repo:
https://github.com/nlpsandbox/aws-cloudformation

The motivation is that we will provide instruction on how to use it in the README. The README of the main org repo would not have been a suitable place for this. Also, maybe this new repo will have a CI/CD workflow that link the repo to AWS.

**Comment by thomasyu888** [comment]
The CF templates have been created.  Now the CI/CD just needs to be linked to auto deploy on aws.

**Comment by tschaffter** [comment]
Nicely done Tom!

I guess a consequence of working with split OpenAPI document, I'm now wondering if we can split a CF template to increase its readability and make it more modular. Here are a couple of links I found when googling around:

- [CloudFormation Stack Splitting and Sharing](https://www.trek10.com/blog/cloudformation-splitting-and-sharing)
- [AWS CloudFormation - Working with nested stacks](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-nested-stacks.html)

I also came around [Troposphere](https://github.com/cloudtools/troposphere) that could make CF writing easier and easier to read.

**Comment by thomasyu888** [comment]
Ya I will create nested stacks to increase modularity.  The issue is you can't use the AWS ui when you have nested stacks. So currently I just have one huge template.

**Comment by thomasyu888** [comment]
The CF templates are created, but just waiting on figuring out nlp-sandbox service user resource conditions.

**Comment by thomasyu888** [comment]
This is done.
