### ISSUE TITLE
Investigate submitted NLP tool logs collected in ELK

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/nlpsandbox-controller#54]
- [x] Show log sample for a message printed using python `logging` package

**Comment by tschaffter** [comment]
I gave additional thought to logging as I was playing with Python `logging` package.

Consider the following code in a controller function:

```
try:
   raise Exception("Sorry, no numbers below zero")
except Exception as error:
   status = 500
   res = Error("Internal error", status, str(error))
```

The `connexion` server respond with a 500 error that has the following response body:

```
{
  "detail": "Sorry, no numbers below zero",
  "status": 500,
  "title": "Internal error"
}
```

Here is the content of the console (not very informative):

```
127.0.0.1 - - [01/Feb/2021 21:09:21] "POST /api/v1/textDateAnnotations HTTP/1.1" 500 -
```

At the cost of adding the line `logging.error(res)` after `res = Error("Internal error", status, str(error))`, we get additional information printed in the console:

```
ERROR:root:{'detail': 'Sorry, no numbers below zero',
 'status': 500,
 'title': 'Internal error',
 'type': None}
```

If the error is not manually caught, the server still returns a 500 error with the following payload:

```
{
  "detail": "The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.",
  "status": 500,
  "title": "Internal Server Error",
  "type": "about:blank"
}
```

and here is the content of the console:

```
[2021-02-01 21:01:56,263] ERROR in app: Exception on /api/v1/textDateAnnotations [POST]
Traceback (most recent call last):
  File "/home/tschaffter/.conda/envs/data-node/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/tschaffter/.conda/envs/data-node/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/tschaffter/.conda/envs/data-node/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/tschaffter/.conda/envs/data-node/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/tschaffter/.conda/envs/data-node/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/tschaffter/.conda/envs/data-node/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/tschaffter/.conda/envs/data-node/lib/python3.9/site-packages/connexion/decorators/decorator.py", line 48, in wrapper
    response = function(request)
  File "/home/tschaffter/.conda/envs/data-node/lib/python3.9/site-packages/connexion/decorators/uri_parsing.py", line 144, in wrapper
    response = function(request)
  File "/home/tschaffter/.conda/envs/data-node/lib/python3.9/site-packages/connexion/decorators/validation.py", line 184, in wrapper
    response = function(request)
  File "/home/tschaffter/.conda/envs/data-node/lib/python3.9/site-packages/connexion/decorators/parameter.py", line 121, in wrapper
    return function(**kwargs)
  File "/mnt/c/Users/thoma/Documents/dev/nlpsandbox/date-annotator-example/server/openapi_server/controllers/text_date_annotation_controller.py", line 25, in create_text_date_annotations
    raise Exception("Sorry, no numbers below zero")
```

## Discussion

### Capture submission and controller logs

By default without logging to the console with `logging.error(...)`, the `connexion` server returns valuable information to the client (here the controller). This is how information is intended to be passed down to the user / client. Therefore I think that given a submission ID, we should be able to retrieve also the log printed by the client / controller.

We should still look at the log of the API server as it may provide useful information like file log traces as shown above then when the exception is not manually caught.

### Debug information

Printing messages can significantly slow an application. Because one of the motivation of this project is to benchmark tools that can be used as they are in production environment, since any change made to their implementation may affect their performance involuntary, I'm concerned about having the tool output lots of (debug) logs. Catching exception in a targetted way, instead of just one `try` and `catch` that surround 200 lines of code (also don't do that), and writing informative messages in the response payload should be the way to go performance wise.

Now if a submission returned a 500 error, it's likely the fault of the developer for not following the above recommendation closely. We can provide support by looking at input that lead the tool to work / fail.

Most importantly, we decided to rely on model / tool validation on public data so that we can return all the logs. It's the purpose of this validation dataset / stage to test methods for edge cases.

Given the above bits of information, I'm not favorable to promote the heavy use of debug messages. Developers can still do it and there is nothing much that we can do. Possibly, heavy logging may hurt the runtime performance of a tool the day we decide to measure and report this value.

### Conclusions

- Given a submission ID, we should be able to access the logs 1) generated by the tool itself and 2) the response received by the client / controller in the event where the response is not 2xx.
- In our documentation, we promote writing try-catch around small block of codes and the writing of informative messages.

**Comment by tschaffter** [comment]
Next I'll try to make a submission to make sure that the stack trace and other logs shown above (submission side) are capture by ELK.

**Comment by tschaffter** [comment]
Using the data annotator example (Python), the stack strace that ended up in the console above is indeed captured by ELK.

![image](https://user-images.githubusercontent.com/3056480/106557690-32535380-64d7-11eb-9822-001470a81ce1.png)

**Comment by tschaffter** [comment]
The above screenshot doesn't show it but by looking at the entire log, we see uWSGI starting, getting an error on the first sample and then shutting down as it should.

**Comment by tschaffter** [comment]
@thomasyu888 Can you annotate the controller logs generated for a given submission ID so that we can easily find them in Kibana?

**Comment by thomasyu888** [comment]
The controller logs are a bit more complicated. What we are probably interested in are the curl commands that are called after the service starts.  So those curl docker containers are named:

```
/{submission_id}_curl_*
```

View this example query: http://10.23.60.253/goto/fabf13821986de507dcd415996d24ac1.

**Comment by tschaffter** [comment]
Is now tracked in the above PR.
