### ISSUE TITLE
Properly enforce submission walltime

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/nlpsandbox-controller#60]
The [current implementation](https://github.com/nlpsandbox/nlpsandbox-controller/blob/dbddae7f3e851d09e5d7daa3956d12f1215bc04c/annotate_note.py#L119) will fail if an iteration of the look gets stuck.

The process responsible for enforcing the walltime should run in a separate thread. A signal should be sent to the benchmarking process to stop waiting for a response from the NLP tool and exit the benchmarking.

**Comment by thomasyu888** [comment]
Agreed.  The current implementation will fail because it may be stuck eternally in a docker run command.  Will have to write separate code to look for the runtime of a submission and stop the docker container of the service which is always named after the submission id.

**Comment by tschaffter** [comment]
@thomasyu888 Can you please give an update on this ticket? Is it a must-have for the launch on June 8th?

**Comment by thomasyu888** [comment]
@tschaffter Not a must have, and have not worked on this ticket

**Comment by tschaffter** [comment]
@thomasyu888 It's OK to not have this enforce at launch time. At first we can replace this by monitoring more closely to see if there is a submission that run for too long.
