### ISSUE TITLE
Failure when running data-node

### ISSUE THREAD

**Issue by gkowalski** [nlpsandbox/nlpsandbox-controller#72]
### Problem description
 
Running the Data Node on a linux server fails . Following directions from https://github.com/MCW-BMI/nlpsandbox-controller/blob/develop/README.md 

#### Steps to reproduce the issue

$ git clone https://github.com/nlpsandbox/data-node.git
Cloning into 'data-node'...
remote: Enumerating objects: 1760, done.
remote: Total 1760 (delta 0), reused 0 (delta 0), pack-reused 1760
Receiving objects: 100% (1760/1760), 449.61 KiB | 0 bytes/s, done.
Resolving deltas: 100% (1230/1230), done.
$ cd data-node/
darvin:/data-node$ cp .env.example .env
darvin:/data-node$ vi .env
darvin:/data-node$ docker-compose up -d
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
[crdw@darvin:~/data-node]$

#### Expected behavior

- Data node starts 

#### Extra information

[crdw@darvin:/data-node]$ docker --version
Docker version 1.13.1, build 0be3e21/1.13.1
[crdw@darvin:/data-node]$
[crdw@darvin:/data-node]$ uname -a
Linux darvin 3.10.0-1160.11.1.el7.x86_64 #1 SMP Fri Dec 18 16:34:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
[crdw@darvin:/data-node]$

**Comment by gkowalski** [comment]
Also wondering why there are not instructions to install this into portaner.io line the workfloworchestrator.

**Comment by thomasyu888** [comment]
This is fixed by adding Docker version requirements in the README.
