### ISSUE TITLE
Add Queue to data endpoint link in config.yaml

### ISSUE THREAD

**Issue by thomasyu888** [nlpsandbox/nlpsandbox-controller#84]
### Is your proposal related to a problem?
Each queue might have to different datanode endpoint, so this must be added to the configuration file.

**Comment by tschaffter** [comment]
@thomasyu888 Can you please give an update on this ticket? Is it a must-have for the launch on June 8th?

**Comment by thomasyu888** [comment]
@tschaffter Not necessary for launch on the 8th.
